server:
  port: 2026
spring:
  application:
    name: crush-post-service
  datasource:
    url: jdbc:mysql://localhost:3306/crush_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
